/* GENERATED by generate_booking_package.py -- do not hand-edit. */
window.BOOKING_DATA = {
  "docType": "proposal",
  "assetDepth": 2,
  "meta": {
    "sampleFlag": false,
    "generatedFrom": "recqb6DGaeJRpymL2",
    "generatedNote": "Generated by generate_booking_package.py from live Airtable fields on 2026-10-01."
  },
  "proposal": {
    "meta": {
      "bookingId": "recqb6DGaeJRpymL2",
      "proposalVersion": "v1",
      "proposalDate": "",
      "programTypeLabel": "Expedition",
      "programWord": "Expedition"
    },
    "summary": "A one-day marine science program for 115 students, organized into four cohorts rotating through hands-on experiences led by REEF educators, from 9:00 AM to 5:00 PM.",
    "scheduleFormat": "rotation",
    "scheduleLabel": "Schedule & Rotations",
    "scheduleDraft": true,
    "rotation": {
      "heading": "Four Cohorts, One Coordinated Day",
      "intro": "Students will be divided into four cohorts of approximately 28\u201329 students. Cohorts rotate among the glass-bottom boat tour, citizen science and fish identification, the lionfish lesson, a scheduled lunch, and two afternoon programs on marine ecology and endangered species. Activities run concurrently, so the schedule below shows where each cohort will be throughout the day.",
      "startTime": "09:00",
      "endTime": "17:00",
      "slotMinutes": 15,
      "cohortSizeLabel": "About 28\u201329 students",
      "cohorts": [
        {
          "id": "A",
          "label": "Cohort A",
          "size": null
        },
        {
          "id": "B",
          "label": "Cohort B",
          "size": null
        },
        {
          "id": "C",
          "label": "Cohort C",
          "size": null
        },
        {
          "id": "D",
          "label": "Cohort D",
          "size": null
        }
      ],
      "stations": [
        {
          "id": "boat",
          "name": "Glass-Bottom Boat Tour",
          "short": "Boat Tour",
          "location": "Park marina",
          "type": "experience",
          "color": 0
        },
        {
          "id": "fishid",
          "name": "Citizen Science & Fish Identification",
          "short": "Fish ID",
          "location": "Pennekamp",
          "type": "experience",
          "color": 1
        },
        {
          "id": "lionfish",
          "name": "Lionfish Lesson & Dissection",
          "short": "Lionfish",
          "location": "Pennekamp",
          "type": "experience",
          "color": 2
        },
        {
          "id": "lunch",
          "name": "Picnic Lunch",
          "short": "Lunch",
          "location": "Park picnic area",
          "type": "meal",
          "color": 3
        },
        {
          "id": "ecology",
          "name": "Marine Ecology",
          "short": "Ecology",
          "location": "Pennekamp",
          "type": "experience",
          "color": 4
        },
        {
          "id": "endangered",
          "name": "Endangered Species",
          "short": "Species",
          "location": "Pennekamp",
          "type": "experience",
          "color": 5
        }
      ],
      "assignments": [
        {
          "cohort": "A",
          "station": "fishid",
          "start": "09:00",
          "end": "10:00"
        },
        {
          "cohort": "A",
          "station": "lionfish",
          "start": "10:00",
          "end": "11:00"
        },
        {
          "cohort": "A",
          "station": "lunch",
          "start": "11:00",
          "end": "12:00"
        },
        {
          "cohort": "A",
          "station": "boat",
          "start": "12:00",
          "end": "14:30"
        },
        {
          "cohort": "A",
          "station": "ecology",
          "start": "14:30",
          "end": "15:30"
        },
        {
          "cohort": "A",
          "station": "endangered",
          "start": "15:30",
          "end": "16:30"
        },
        {
          "cohort": "B",
          "station": "lionfish",
          "start": "09:00",
          "end": "10:00"
        },
        {
          "cohort": "B",
          "station": "fishid",
          "start": "10:00",
          "end": "11:00"
        },
        {
          "cohort": "B",
          "station": "lunch",
          "start": "11:00",
          "end": "12:00"
        },
        {
          "cohort": "B",
          "station": "boat",
          "start": "12:00",
          "end": "14:30"
        },
        {
          "cohort": "B",
          "station": "ecology",
          "start": "14:30",
          "end": "15:30"
        },
        {
          "cohort": "B",
          "station": "endangered",
          "start": "15:30",
          "end": "16:30"
        },
        {
          "cohort": "C",
          "station": "boat",
          "start": "09:00",
          "end": "11:30"
        },
        {
          "cohort": "C",
          "station": "lunch",
          "start": "11:30",
          "end": "12:30"
        },
        {
          "cohort": "C",
          "station": "fishid",
          "start": "12:30",
          "end": "13:30"
        },
        {
          "cohort": "C",
          "station": "lionfish",
          "start": "13:30",
          "end": "14:30"
        },
        {
          "cohort": "C",
          "station": "endangered",
          "start": "14:30",
          "end": "15:30"
        },
        {
          "cohort": "C",
          "station": "ecology",
          "start": "15:30",
          "end": "16:30"
        },
        {
          "cohort": "D",
          "station": "boat",
          "start": "09:00",
          "end": "11:30"
        },
        {
          "cohort": "D",
          "station": "lunch",
          "start": "11:30",
          "end": "12:30"
        },
        {
          "cohort": "D",
          "station": "lionfish",
          "start": "12:30",
          "end": "13:30"
        },
        {
          "cohort": "D",
          "station": "fishid",
          "start": "13:30",
          "end": "14:30"
        },
        {
          "cohort": "D",
          "station": "endangered",
          "start": "14:30",
          "end": "15:30"
        },
        {
          "cohort": "D",
          "station": "ecology",
          "start": "15:30",
          "end": "16:30"
        }
      ],
      "departure": {
        "time": "17:00",
        "label": "Departure",
        "note": "The program day ends at 5:00 PM, when buses return to pick up students. The final half hour is flexible time for wrap-up."
      },
      "notes": [
        "This is a planning schedule. Exact activity order, timing, and locations may be refined before the program, and REEF will confirm the final schedule with you.",
        "The glass-bottom boat tour is planned as a 2.5-hour program for every cohort. Citizen science and fish identification, the lionfish lesson, marine ecology, and endangered species are each planned as one-hour programs, with time between activities for transitions.",
        "Every cohort has the same one-hour lunch. Lunch periods are staggered so the picnic area is not crowded.",
        "Your school provides bus transportation. Your group arrives on three buses for a 9:00 AM drop-off, and the buses return to pick students up at 5:00 PM."
      ],
      "startLabel": "9:00 AM",
      "endLabel": "5:00 PM"
    },
    "pendingNote": "Your detailed schedule is still being finalized. Rose will share exact times before your contract is prepared. The activities below are included either way.",
    "group": {
      "orgName": "Ben Gamla Charter School",
      "contactName": "Lindsay Pollack",
      "contactLabel": "School Contact",
      "contactLine": "Lindsay Pollack, Dean of Students",
      "gradeLevel": "Dean of Students",
      "students": 115,
      "chaperones": 10
    },
    "dates": {
      "label": "Proposed",
      "range": "March 17, 2027"
    },
    "location": "John Pennekamp Coral Reef State Park, Key Largo",
    "hours": "9:00 AM\u20135:00 PM",
    "roadmap": {
      "steps": [
        "Inquiry",
        "Proposal Prepared",
        "Your Review",
        "Contract",
        "Confirmed"
      ],
      "currentStep": 2
    },
    "cta": {
      "primaryText": "Looks Good \u2014 Prepare My Contract",
      "confirmButtonText": "Approve Proposal",
      "primaryConfirmHeadline": "Thank you \u2014 your proposal is approved.",
      "primaryConfirmBody": "Rose will prepare your contract and confirm any remaining details with you by email. Approving doesn't sign anything or commit a payment; the contract is the next step.",
      "secondaryText": "Request a Change",
      "changeFormLabel": "Tell us about any requested changes to cohort assignments, activity timing, group size, transportation, meals, accessibility needs, or program content.",
      "changeConfirmHeadline": "Thank you \u2014 your change request is on its way.",
      "changeConfirmBody": "Rose will follow up by email and send a revised proposal if anything changes.",
      "contactEmail": "rose@REEF.org",
      "responseWebhookUrl": "https://hooks.zapier.com/hooks/catch/28743322/4hv7eqd/"
    },
    "confirmSummary": [
      {
        "k": "Date",
        "v": "Wednesday, March 17, 2027"
      },
      {
        "k": "Group",
        "v": "115 students and 10 chaperones (all 10 complimentary)"
      },
      {
        "k": "Format",
        "v": "Four cohorts rotating through five hands-on experiences"
      },
      {
        "k": "Activities",
        "v": "Glass-Bottom Boat Tour, Citizen Science & Fish Identification, Lionfish Lesson & Dissection, Marine Ecology, and Endangered Species"
      },
      {
        "k": "Location & hours",
        "v": "John Pennekamp Coral Reef State Park, Key Largo, 9:00 AM\u20135:00 PM"
      },
      {
        "k": "Estimated total",
        "v": "$19,920.60"
      },
      {
        "k": "Not included",
        "v": "Meals and transportation to and from the park, which your school arranges"
      }
    ],
    "nextSteps": [
      "Review each section of this proposal with your team",
      "Select \u201cLooks Good \u2014 Prepare My Contract,\u201d or \u201cRequest a Change\u201d if anything needs adjusting",
      "Rose prepares your contract with the payment schedule, starting with a $500 deposit to hold your date",
      "Once the contract is signed, REEF confirms final logistics with you, including cohort assignments, activity order and timing, arrival and pickup details, and what to bring"
    ],
    "reefContact": {
      "name": "Rose Kelly",
      "role": "Education Coordinator",
      "photo": null,
      "welcomeLine": "Rose has been building your group's itinerary and is your direct point of contact through booking.",
      "email": "rose@REEF.org",
      "phone": "305-852-0030"
    },
    "welcome": {
      "body": [
        "Rose has been building your group's itinerary and is your direct point of contact through booking."
      ],
      "signOff": "Rose Kelly"
    },
    "glance": [
      {
        "k": "Date",
        "v": "March 17, 2027"
      },
      {
        "k": "Group Size",
        "v": "115 students + 10 chaperones"
      },
      {
        "k": "Program Hours",
        "v": "9:00 AM\u20135:00 PM"
      },
      {
        "k": "Location",
        "v": "John Pennekamp Coral Reef State Park, Key Largo"
      },
      {
        "k": "Format",
        "v": "Four cohorts rotating through five hands-on experiences",
        "wide": true
      },
      {
        "k": "Focus",
        "v": "Florida Keys Ecology \u00b7 Marine Ecology \u00b7 Invasive Species \u00b7 Hands-on Lab \u00b7 Citizen Science \u00b7 Caribbean Fish ID",
        "wide": true
      }
    ],
    "pillars": [
      {
        "title": "Real citizen science, not a demo",
        "text": "Students are trained in REEF's Volunteer Fish Survey Project methods and collect survey data using the same protocol REEF's volunteer network uses across the Caribbean and beyond."
      },
      {
        "title": "Taught by REEF educators",
        "text": "Every session and field activity is led by REEF marine science educators, with pre- and post-activity debriefs that connect what students saw to what it means."
      },
      {
        "title": "The Florida Keys as the classroom",
        "text": "Programs are based at REEF's Ocean Exploration Center in Key Largo and run out into the coral reef, mangrove, and seagrass habitats that surround it."
      },
      {
        "title": "Built around your group",
        "text": "The itinerary in this proposal is shaped around your dates, group size, and what you told us your students need to get out of the trip."
      }
    ],
    "team": [
      {
        "name": "REEF Marine Science Educators",
        "role": "Program Instruction",
        "bio": "Lead every session and field activity, from fish ID training through the reef survey itself."
      },
      {
        "name": "Volunteer Fish Survey Project Staff",
        "role": "Citizen Science",
        "bio": "Run REEF's survey methodology training and help students log real observations into REEF's database."
      },
      {
        "name": "REEF Ocean Explorers Coordination",
        "role": "Trip Logistics",
        "bio": "Your planning contact for dates, headcount, vendors, and everything between booking and arrival."
      }
    ],
    "days": [
      {
        "dayNumber": 1,
        "totalDays": 1,
        "title": "One Day on the Reef",
        "theme": "Four cohorts rotate through five hands-on experiences led by REEF educators, from 9:00 AM to 5:00 PM.",
        "blocks": [
          {
            "station": "boat",
            "tag": "Field Experience",
            "title": "Glass-Bottom Boat Tour",
            "description": "Students view living coral reef habitat and the fish that depend on it from a glass-bottom boat, with a REEF educator helping them connect what they see to how healthy reefs work.",
            "when": "Cohorts C & D: 9:00\u201311:30 AM \u00b7 Cohorts A & B: 12:00\u20132:30 PM",
            "color": 0,
            "location": "Park marina"
          },
          {
            "station": "fishid",
            "tag": "Citizen Science",
            "title": "Citizen Science & Fish Identification",
            "description": "Students learn how REEF's volunteer divers and snorkelers identify fish and record what they see, then practice the same identification and survey skills used in REEF's Volunteer Fish Survey Project.",
            "when": "Cohort A: 9:00\u201310:00 AM \u00b7 Cohort B: 10:00\u201311:00 AM \u00b7 Cohort C: 12:30\u20131:30 PM \u00b7 Cohort D: 1:30\u20132:30 PM",
            "color": 1,
            "location": "Pennekamp"
          },
          {
            "station": "lionfish",
            "tag": "Hands-On Lab",
            "title": "Lionfish Lesson & Dissection",
            "description": "Students investigate invasive lionfish through a guided dissection, looking at anatomy and adaptations and learning why lionfish are a conservation challenge for Florida Keys reefs.",
            "when": "Cohort B: 9:00\u201310:00 AM \u00b7 Cohort A: 10:00\u201311:00 AM \u00b7 Cohort D: 12:30\u20131:30 PM \u00b7 Cohort C: 1:30\u20132:30 PM",
            "color": 2,
            "location": "Pennekamp"
          },
          {
            "station": "lunch",
            "tag": "Break",
            "title": "Picnic Lunch",
            "description": "Each cohort has the same one-hour picnic lunch. Lunch is not provided, so students and chaperones should bring a packed lunch.",
            "when": "Cohorts A & B: 11:00 AM\u201312:00 PM \u00b7 Cohorts C & D: 11:30 AM\u201312:30 PM",
            "color": 3,
            "location": "Park picnic area"
          },
          {
            "station": "ecology",
            "tag": "Education",
            "title": "Marine Ecology",
            "description": "A REEF educator-led program on how reef, seagrass, and mangrove communities work and how the species within them depend on one another. Two cohorts join each one-hour session.",
            "when": "Cohorts A & B: 2:30\u20133:30 PM \u00b7 Cohorts C & D: 3:30\u20134:30 PM",
            "color": 4,
            "location": "Pennekamp"
          },
          {
            "station": "endangered",
            "tag": "Education",
            "title": "Endangered Species",
            "description": "A REEF educator-led program on threatened and endangered species of the Florida Keys, why they are at risk, and what people can do to help protect them. Two cohorts join each one-hour session.",
            "when": "Cohorts C & D: 2:30\u20133:30 PM \u00b7 Cohorts A & B: 3:30\u20134:30 PM",
            "color": 5,
            "location": "Pennekamp"
          }
        ],
        "studentsWill": [
          "Observe living coral reef habitat and marine life from the glass-bottom boat.",
          "Learn and practice the fish identification and survey methods REEF's citizen scientists use.",
          "Investigate invasive lionfish anatomy and adaptations through a guided dissection.",
          "Explore how marine ecosystems function and why some Florida Keys species are endangered.",
          "Connect what they see to REEF's ongoing reef conservation and invasive-species work."
        ],
        "outcomesNote": null
      }
    ],
    "included": [
      {
        "title": "Included in your Expedition",
        "items": [
          "Glass-bottom boat tour admission for all 115 students and 10 chaperones, including the boat gratuity",
          "REEF-led programming: citizen science and fish identification training, and the lionfish lesson and dissection",
          "REEF-led afternoon programs on marine ecology and endangered species",
          "Instructional materials and REEF survey supplies for every student",
          "Lionfish specimens for the dissection",
          "John Pennekamp Coral Reef State Park entrance fees for your three buses",
          "A follow-up lesson using the survey data your students collect"
        ]
      }
    ],
    "notIncluded": [
      "Meals \u2014 lunch time is built into the schedule, but food is not provided. Students and chaperones bring a packed lunch, and REEF staff can recommend delivery options",
      "Transportation to and from the park, which your school arranges. Transportation between the park and other locations, including REEF's campus, is still being explored and is not part of this proposal"
    ],
    "optional": [],
    "photos": {
      "overview": "photos/overview.jpeg",
      "experience": "photos/experience.png",
      "days": "photos/days.jpeg",
      "included": "photos/included.jpeg"
    },
    "photoCredits": {},
    "pricing": {
      "tileTotal": {
        "label": "Estimated Total",
        "num": "$19,920.60",
        "unit": "for 115 students and 10 chaperones"
      },
      "tileRate": {
        "label": "Per Student",
        "num": "$173.22",
        "unit": "per student for the full Expedition"
      },
      "tileChaperones": {
        "label": "Complimentary Chaperones",
        "num": "10 of 10",
        "unit": "chaperone spaces at no charge"
      },
      "chaperonePolicy": {
        "headline": "All 10 chaperones are complimentary.",
        "lines": [
          "One chaperone space is complimentary for every 9 people in your group, counting students and chaperones together. Your group of 115 students and 10 chaperones (125 people) earns 13 complimentary spaces.",
          "With 115 students, you can bring up to 14 chaperones before any chaperone is billed.",
          "Each additional chaperone beyond the complimentary spaces pays the full per-participant package price, the same as a student."
        ]
      },
      "estimatedTotal": "$19,920.60",
      "estimatedTotalNote": "<strong>$19,920.60</strong> is your estimated total, based on the details below. It includes REEF's program fees and every item listed under What's Included. If anything below changes, REEF will send a revised proposal with an updated total.",
      "assumptions": [
        "115 students and 10 chaperones, with all 10 chaperone spaces complimentary",
        "One program day: Wednesday, March 17, 2027, 9:00 AM to 5:00 PM",
        "Four cohorts rotating through the glass-bottom boat tour, citizen science and fish identification, the lionfish lesson and dissection, and afternoon marine ecology and endangered species programs",
        "This is a planning schedule: exact activity order, timing, and locations may be refined before the program",
        "All activities take place at John Pennekamp Coral Reef State Park, with no sessions at REEF's campus; if transportation between the park and REEF's campus is arranged later, REEF will update the proposal",
        "Your school provides bus transportation to and from the park: three buses arrive for a 9:00 AM drop-off and return to pick up students at 5:00 PM (park entrance is charged per bus)",
        "Elementary (K\u20136) glass-bottom boat rates for students"
      ],
      "whatCouldChange": [
        "Changes to your student or chaperone count",
        "A different date or program hours",
        "Adding or removing activities"
      ]
    },
    "share": {
      "status": "draft",
      "statusLabel": "Draft",
      "version": "v1",
      "lastUpdated": "Oct 1, 2026",
      "needs": [
        {
          "key": "approval",
          "label": "Get school or organizational approval",
          "view": "administrator"
        },
        {
          "key": "staff",
          "label": "Review with teachers or program staff",
          "view": "educator"
        },
        {
          "key": "families",
          "label": "Share information with parents or chaperones",
          "view": "family"
        },
        {
          "key": "students",
          "label": "Build student or participant excitement",
          "view": "student"
        },
        {
          "key": "changes",
          "label": "Request changes from REEF",
          "action": "change"
        }
      ],
      "views": [
        {
          "key": "administrator",
          "title": "Administrator Approval Summary",
          "audience": "Ben Gamla school leadership",
          "description": "A concise summary for the person who approves the program: purpose, logistics, responsibilities, price, and terms.",
          "includes": [
            "Purpose and educational value",
            "Date, location, hours and group size",
            "Schedule overview",
            "Safety, supervision, transportation and meals",
            "Price, inclusions and terms",
            "Outstanding decisions"
          ],
          "path": "share/administrator/",
          "url": "https://reef-environmental-education-foundation.github.io/reef-program-pages/bookings/ben-gamla-charter-school/share/administrator/",
          "pricing": true
        },
        {
          "key": "educator",
          "title": "Draft Educator Plan",
          "audience": "Ben Gamla teachers and program staff",
          "description": "The planning view for teachers: learning objectives, the full schedule, and the logistics your team coordinates.",
          "includes": [
            "Learning objectives",
            "Full schedule and cohort rotation",
            "Teacher and chaperone assignments",
            "Arrival, lunch and departure logistics",
            "What to bring and supervision",
            "Preparation resources"
          ],
          "path": "share/educator/",
          "url": "https://reef-environmental-education-foundation.github.io/reef-program-pages/bookings/ben-gamla-charter-school/share/educator/",
          "pricing": true
        },
        {
          "key": "family",
          "title": "Family & Chaperone Overview",
          "audience": "Ben Gamla parents, guardians and chaperones",
          "description": "What students will experience and how to prepare. No pricing or contract terms.",
          "includes": [
            "What students will experience",
            "Date and general location",
            "A simple schedule",
            "What to wear and bring",
            "Lunch and transportation",
            "Chaperone expectations"
          ],
          "path": "share/family/",
          "url": "https://reef-environmental-education-foundation.github.io/reef-program-pages/bookings/ben-gamla-charter-school/share/family/",
          "pricing": false
        },
        {
          "key": "student",
          "title": "Student Preview",
          "audience": "Ben Gamla students",
          "description": "A short, visual preview to build excitement before the day.",
          "includes": [
            "The activities students will do",
            "Marine science topics",
            "What the day will feel like",
            "What to bring"
          ],
          "path": "share/student/",
          "url": "https://reef-environmental-education-foundation.github.io/reef-program-pages/bookings/ben-gamla-charter-school/share/student/",
          "pricing": false
        }
      ],
      "roles": [
        {
          "name": "Lindsay Pollack",
          "title": "Dean of Students",
          "roles": [
            "coordinator"
          ],
          "roleLabels": [
            "Primary coordinator"
          ],
          "approvalAuthority": false,
          "audiences": [
            "administrator",
            "educator",
            "family",
            "student"
          ],
          "note": ""
        },
        {
          "name": "",
          "title": "School leadership",
          "roles": [
            "decisionMaker"
          ],
          "roleLabels": [
            "Authorized decision-maker"
          ],
          "approvalAuthority": true,
          "audiences": [
            "administrator"
          ],
          "note": "To be confirmed by the school"
        },
        {
          "name": "",
          "title": "Teachers and program staff",
          "roles": [
            "planningTeam"
          ],
          "roleLabels": [
            "Planning team"
          ],
          "approvalAuthority": false,
          "audiences": [
            "educator"
          ],
          "note": ""
        },
        {
          "name": "",
          "title": "Parents, guardians and chaperones",
          "roles": [
            "audience"
          ],
          "roleLabels": [
            "Read-only audience"
          ],
          "approvalAuthority": false,
          "audiences": [
            "family"
          ],
          "note": ""
        },
        {
          "name": "",
          "title": "Students",
          "roles": [
            "audience"
          ],
          "roleLabels": [
            "Read-only audience"
          ],
          "approvalAuthority": false,
          "audiences": [
            "student"
          ],
          "note": ""
        }
      ],
      "privacyNote": "Anyone who has a link can open that page. The family and student views leave out pricing and contract terms entirely. Please don't add student names or other private details to anything you share."
    }
  }
};
