/* GENERATED by generate_booking_package.py -- do not hand-edit. Contains ONLY the fields this audience view shows. */
window.BOOKING_DATA = {
  "docType": "audience",
  "assetDepth": 4,
  "meta": {
    "sampleFlag": false
  },
  "view": {
    "status": "draft",
    "statusLabel": "Draft",
    "version": "v1",
    "lastUpdated": "Oct 1, 2026",
    "orgName": "Ben Gamla Charter School",
    "dateLine": "March 17, 2027",
    "hours": "9:00 AM\u20135:00 PM",
    "programName": "Florida Keys Ocean Explorers Expedition",
    "summary": "A one-day marine science program for 115 students, organized into four cohorts rotating through hands-on experiences led by REEF educators, from 9:00 AM to 5:00 PM.",
    "scheduleDraft": true,
    "view": "family",
    "location": "John Pennekamp Coral Reef State Park, Key Largo",
    "intro": "Students will spend a day with REEF educators, working in small groups that rotate through hands-on marine science experiences. This is a draft planning schedule; REEF will confirm final timing and locations.",
    "experiences": [
      {
        "title": "Glass-Bottom Boat Tour",
        "text": "Students view living coral reef habitat and the fish that depend on it from a glass-bottom boat, with a REEF educator helping them connect what they see to how healthy reefs work.",
        "color": 0
      },
      {
        "title": "Citizen Science & Fish Identification",
        "text": "Students learn how REEF's volunteer divers and snorkelers identify fish and record what they see, then practice the same identification and survey skills used in REEF's Volunteer Fish Survey Project.",
        "color": 1
      },
      {
        "title": "Lionfish Lesson & Dissection",
        "text": "Students investigate invasive lionfish through a guided dissection, looking at anatomy and adaptations and learning why lionfish are a conservation challenge for Florida Keys reefs.",
        "color": 2
      },
      {
        "title": "Marine Ecology",
        "text": "A REEF educator-led program on how reef, seagrass, and mangrove communities work and how the species within them depend on one another. Two cohorts join each one-hour session.",
        "color": 4
      },
      {
        "title": "Endangered Species",
        "text": "A REEF educator-led program on threatened and endangered species of the Florida Keys, why they are at risk, and what people can do to help protect them. Two cohorts join each one-hour session.",
        "color": 5
      }
    ],
    "whyItMatters": [
      "Students are trained in REEF's Volunteer Fish Survey Project methods and collect survey data using the same protocol REEF's volunteer network uses across the Caribbean and beyond.",
      "Every session and field activity is led by REEF marine science educators, with pre- and post-activity debriefs that connect what students saw to what it means."
    ],
    "schedule": [
      {
        "time": "9:00 AM",
        "label": "Program begins. Students work in 4 small groups (cohorts) that rotate between activities."
      },
      {
        "time": "11:00 AM\u201312:30 PM",
        "label": "Picnic lunch. Each cohort has its own lunch time in this window."
      },
      {
        "time": "5:00 PM",
        "label": "Program ends."
      }
    ],
    "bring": [
      "A packed lunch"
    ],
    "clothing": [],
    "lunch": "Packed lunches from home. Each cohort eats at its own scheduled time in the park picnic area, between 11:00 AM and 12:30 PM.",
    "transportation": "Students travel to and from the park by school bus, with drop-off at 9:00 AM and pick-up at 5:00 PM. Your school will share departure and return times.",
    "chaperoneExpectations": [
      "Teachers and adult chaperones accompanying the group are directly responsible for students at all times, including during free time and meals."
    ],
    "deadlines": [],
    "fundraising": null,
    "aboutReef": "REEF (Reef Environmental Education Foundation) is a marine conservation nonprofit based in Key Largo, Florida. Since 1990, REEF has trained volunteer divers and snorkelers to identify and survey fish through the Volunteer Fish Survey Project, building one of the world's largest marine life databases. REEF educators bring that same hands-on, science-first approach to every student program.",
    "contactInstructions": "Questions about the day? Please contact your child's school.",
    "title": "Family & Chaperone Overview",
    "audienceLabel": "Ben Gamla parents, guardians and chaperones",
    "url": "https://reef-environmental-education-foundation.github.io/reef-program-pages/bookings/ben-gamla-charter-school/share/family/"
  }
};
