/* GENERATED by generate_booking_package.py -- do not hand-edit. Contains ONLY the fields this audience view shows. */
window.BOOKING_DATA = {
  "docType": "audience",
  "assetDepth": 4,
  "meta": {
    "sampleFlag": false
  },
  "view": {
    "status": "draft",
    "statusLabel": "Draft",
    "version": "v1",
    "lastUpdated": "Oct 1, 2026",
    "orgName": "Ben Gamla Charter School",
    "dateLine": "March 17, 2027",
    "hours": "9:00 AM\u20135:00 PM",
    "programName": "Florida Keys Ocean Explorers Expedition",
    "summary": "A one-day marine science program for 115 students, organized into four cohorts rotating through hands-on experiences led by REEF educators, from 9:00 AM to 5:00 PM.",
    "scheduleDraft": true,
    "view": "educator",
    "objectives": [
      "Observe living coral reef habitat and marine life from the glass-bottom boat.",
      "Learn and practice the fish identification and survey methods REEF's citizen scientists use.",
      "Investigate invasive lionfish anatomy and adaptations through a guided dissection.",
      "Explore how marine ecosystems function and why some Florida Keys species are endangered.",
      "Connect what they see to REEF's ongoing reef conservation and invasive-species work."
    ],
    "scheduleFormat": "rotation",
    "rotation": {
      "heading": "Four Cohorts, One Coordinated Day",
      "intro": "Students will be divided into four cohorts of approximately 28\u201329 students. Cohorts rotate among the glass-bottom boat tour, citizen science and fish identification, the lionfish lesson, a scheduled lunch, and two afternoon programs on marine ecology and endangered species. Activities run concurrently, so the schedule below shows where each cohort will be throughout the day.",
      "startTime": "09:00",
      "endTime": "17:00",
      "slotMinutes": 15,
      "cohortSizeLabel": "About 28\u201329 students",
      "cohorts": [
        {
          "id": "A",
          "label": "Cohort A",
          "size": null
        },
        {
          "id": "B",
          "label": "Cohort B",
          "size": null
        },
        {
          "id": "C",
          "label": "Cohort C",
          "size": null
        },
        {
          "id": "D",
          "label": "Cohort D",
          "size": null
        }
      ],
      "stations": [
        {
          "id": "boat",
          "name": "Glass-Bottom Boat Tour",
          "short": "Boat Tour",
          "location": "Park marina",
          "type": "experience",
          "color": 0
        },
        {
          "id": "fishid",
          "name": "Citizen Science & Fish Identification",
          "short": "Fish ID",
          "location": "Pennekamp",
          "type": "experience",
          "color": 1
        },
        {
          "id": "lionfish",
          "name": "Lionfish Lesson & Dissection",
          "short": "Lionfish",
          "location": "Pennekamp",
          "type": "experience",
          "color": 2
        },
        {
          "id": "lunch",
          "name": "Picnic Lunch",
          "short": "Lunch",
          "location": "Park picnic area",
          "type": "meal",
          "color": 3
        },
        {
          "id": "ecology",
          "name": "Marine Ecology",
          "short": "Ecology",
          "location": "Pennekamp",
          "type": "experience",
          "color": 4
        },
        {
          "id": "endangered",
          "name": "Endangered Species",
          "short": "Species",
          "location": "Pennekamp",
          "type": "experience",
          "color": 5
        }
      ],
      "assignments": [
        {
          "cohort": "A",
          "station": "fishid",
          "start": "09:00",
          "end": "10:00"
        },
        {
          "cohort": "A",
          "station": "lionfish",
          "start": "10:00",
          "end": "11:00"
        },
        {
          "cohort": "A",
          "station": "lunch",
          "start": "11:00",
          "end": "12:00"
        },
        {
          "cohort": "A",
          "station": "boat",
          "start": "12:00",
          "end": "14:30"
        },
        {
          "cohort": "A",
          "station": "ecology",
          "start": "14:30",
          "end": "15:30"
        },
        {
          "cohort": "A",
          "station": "endangered",
          "start": "15:30",
          "end": "16:30"
        },
        {
          "cohort": "B",
          "station": "lionfish",
          "start": "09:00",
          "end": "10:00"
        },
        {
          "cohort": "B",
          "station": "fishid",
          "start": "10:00",
          "end": "11:00"
        },
        {
          "cohort": "B",
          "station": "lunch",
          "start": "11:00",
          "end": "12:00"
        },
        {
          "cohort": "B",
          "station": "boat",
          "start": "12:00",
          "end": "14:30"
        },
        {
          "cohort": "B",
          "station": "ecology",
          "start": "14:30",
          "end": "15:30"
        },
        {
          "cohort": "B",
          "station": "endangered",
          "start": "15:30",
          "end": "16:30"
        },
        {
          "cohort": "C",
          "station": "boat",
          "start": "09:00",
          "end": "11:30"
        },
        {
          "cohort": "C",
          "station": "lunch",
          "start": "11:30",
          "end": "12:30"
        },
        {
          "cohort": "C",
          "station": "fishid",
          "start": "12:30",
          "end": "13:30"
        },
        {
          "cohort": "C",
          "station": "lionfish",
          "start": "13:30",
          "end": "14:30"
        },
        {
          "cohort": "C",
          "station": "endangered",
          "start": "14:30",
          "end": "15:30"
        },
        {
          "cohort": "C",
          "station": "ecology",
          "start": "15:30",
          "end": "16:30"
        },
        {
          "cohort": "D",
          "station": "boat",
          "start": "09:00",
          "end": "11:30"
        },
        {
          "cohort": "D",
          "station": "lunch",
          "start": "11:30",
          "end": "12:30"
        },
        {
          "cohort": "D",
          "station": "lionfish",
          "start": "12:30",
          "end": "13:30"
        },
        {
          "cohort": "D",
          "station": "fishid",
          "start": "13:30",
          "end": "14:30"
        },
        {
          "cohort": "D",
          "station": "endangered",
          "start": "14:30",
          "end": "15:30"
        },
        {
          "cohort": "D",
          "station": "ecology",
          "start": "15:30",
          "end": "16:30"
        }
      ],
      "departure": {
        "time": "17:00",
        "label": "Departure",
        "note": "The program day ends at 5:00 PM, when buses return to pick up students. The final half hour is flexible time for wrap-up."
      },
      "notes": [
        "This is a planning schedule. Exact activity order, timing, and locations may be refined before the program, and REEF will confirm the final schedule with you.",
        "The glass-bottom boat tour is planned as a 2.5-hour program for every cohort. Citizen science and fish identification, the lionfish lesson, marine ecology, and endangered species are each planned as one-hour programs, with time between activities for transitions.",
        "Every cohort has the same one-hour lunch. Lunch periods are staggered so the picnic area is not crowded.",
        "Your school provides bus transportation. Your group arrives on three buses for a 9:00 AM drop-off, and the buses return to pick students up at 5:00 PM."
      ],
      "startLabel": "9:00 AM",
      "endLabel": "5:00 PM"
    },
    "days": [
      {
        "dayNumber": 1,
        "totalDays": 1,
        "title": "One Day on the Reef",
        "theme": "Four cohorts rotate through five hands-on experiences led by REEF educators, from 9:00 AM to 5:00 PM.",
        "blocks": [
          {
            "station": "boat",
            "tag": "Field Experience",
            "title": "Glass-Bottom Boat Tour",
            "description": "Students view living coral reef habitat and the fish that depend on it from a glass-bottom boat, with a REEF educator helping them connect what they see to how healthy reefs work.",
            "when": "Cohorts C & D: 9:00\u201311:30 AM \u00b7 Cohorts A & B: 12:00\u20132:30 PM",
            "color": 0,
            "location": "Park marina"
          },
          {
            "station": "fishid",
            "tag": "Citizen Science",
            "title": "Citizen Science & Fish Identification",
            "description": "Students learn how REEF's volunteer divers and snorkelers identify fish and record what they see, then practice the same identification and survey skills used in REEF's Volunteer Fish Survey Project.",
            "when": "Cohort A: 9:00\u201310:00 AM \u00b7 Cohort B: 10:00\u201311:00 AM \u00b7 Cohort C: 12:30\u20131:30 PM \u00b7 Cohort D: 1:30\u20132:30 PM",
            "color": 1,
            "location": "Pennekamp"
          },
          {
            "station": "lionfish",
            "tag": "Hands-On Lab",
            "title": "Lionfish Lesson & Dissection",
            "description": "Students investigate invasive lionfish through a guided dissection, looking at anatomy and adaptations and learning why lionfish are a conservation challenge for Florida Keys reefs.",
            "when": "Cohort B: 9:00\u201310:00 AM \u00b7 Cohort A: 10:00\u201311:00 AM \u00b7 Cohort D: 12:30\u20131:30 PM \u00b7 Cohort C: 1:30\u20132:30 PM",
            "color": 2,
            "location": "Pennekamp"
          },
          {
            "station": "lunch",
            "tag": "Break",
            "title": "Picnic Lunch",
            "description": "Each cohort has the same one-hour picnic lunch. Lunch is not provided, so students and chaperones should bring a packed lunch.",
            "when": "Cohorts A & B: 11:00 AM\u201312:00 PM \u00b7 Cohorts C & D: 11:30 AM\u201312:30 PM",
            "color": 3,
            "location": "Park picnic area"
          },
          {
            "station": "ecology",
            "tag": "Education",
            "title": "Marine Ecology",
            "description": "A REEF educator-led program on how reef, seagrass, and mangrove communities work and how the species within them depend on one another. Two cohorts join each one-hour session.",
            "when": "Cohorts A & B: 2:30\u20133:30 PM \u00b7 Cohorts C & D: 3:30\u20134:30 PM",
            "color": 4,
            "location": "Pennekamp"
          },
          {
            "station": "endangered",
            "tag": "Education",
            "title": "Endangered Species",
            "description": "A REEF educator-led program on threatened and endangered species of the Florida Keys, why they are at risk, and what people can do to help protect them. Two cohorts join each one-hour session.",
            "when": "Cohorts C & D: 2:30\u20133:30 PM \u00b7 Cohorts A & B: 3:30\u20134:30 PM",
            "color": 5,
            "location": "Pennekamp"
          }
        ],
        "studentsWill": [
          "Observe living coral reef habitat and marine life from the glass-bottom boat.",
          "Learn and practice the fish identification and survey methods REEF's citizen scientists use.",
          "Investigate invasive lionfish anatomy and adaptations through a guided dissection.",
          "Explore how marine ecosystems function and why some Florida Keys species are endangered.",
          "Connect what they see to REEF's ongoing reef conservation and invasive-species work."
        ],
        "outcomesNote": null
      }
    ],
    "pendingNote": null,
    "cohortAssignments": [
      {
        "cohort": "Cohort A",
        "size": null,
        "teachers": "",
        "chaperones": ""
      },
      {
        "cohort": "Cohort B",
        "size": null,
        "teachers": "",
        "chaperones": ""
      },
      {
        "cohort": "Cohort C",
        "size": null,
        "teachers": "",
        "chaperones": ""
      },
      {
        "cohort": "Cohort D",
        "size": null,
        "teachers": "",
        "chaperones": ""
      }
    ],
    "assignmentsNote": "Your school assigns teachers and chaperones to each cohort. Use this table to plan, then share the final assignments with REEF.",
    "logistics": [
      {
        "k": "Arrival",
        "v": "Buses arrive at John Pennekamp Coral Reef State Park for a 9:00 AM start."
      },
      {
        "k": "Transitions",
        "v": "Short gaps between activities are transition time for moving between the marina, the picnic area and program areas. This is a planning schedule, so exact timing may be refined before the program."
      },
      {
        "k": "Lunch",
        "v": "Packed lunches from home. Each cohort eats at its own scheduled time in the park picnic area, between 11:00 AM and 12:30 PM."
      },
      {
        "k": "Departure",
        "v": "The program day ends at 5:00 PM, when buses return to pick up students."
      }
    ],
    "bring": [
      "A packed lunch"
    ],
    "accessibility": null,
    "supervision": [
      "Teachers and adult chaperones accompanying the group are directly responsible for students at all times, including during free time and meals.",
      "An adult chaperone must accompany student groups with participants under 18."
    ],
    "counts": {
      "students": 115,
      "chaperones": 10
    },
    "resources": [
      "Learn about REEF's Volunteer Fish Survey Project and fish identification resources at www.REEF.org."
    ],
    "remaining": [
      "Final student and chaperone headcount",
      "Exact cohort sizes and which students are in each cohort",
      "Teacher and chaperone assignments for each cohort",
      "Final activity order and timing (this is a planning schedule)",
      "Whether any programs can move to the REEF campus (this depends on transportation between the park and campus, which is still being explored and is not confirmed)"
    ],
    "reefContact": {
      "name": "Rose Kelly",
      "role": "Education Coordinator",
      "email": "rose@REEF.org",
      "phone": "305-852-0030"
    },
    "title": "Draft Educator Plan",
    "audienceLabel": "Ben Gamla teachers and program staff",
    "url": "https://reef-environmental-education-foundation.github.io/reef-program-pages/bookings/ben-gamla-charter-school/share/educator/"
  }
};
