/* GENERATED by generate_booking_package.py -- do not hand-edit. Contains ONLY the fields this audience view shows. */
window.BOOKING_DATA = {
  "docType": "audience",
  "assetDepth": 4,
  "meta": {
    "sampleFlag": false
  },
  "view": {
    "status": "draft",
    "statusLabel": "Draft",
    "version": "v1",
    "lastUpdated": "Oct 1, 2026",
    "orgName": "Ben Gamla Charter School",
    "dateLine": "March 17, 2027",
    "hours": "9:00 AM\u20135:00 PM",
    "programName": "Florida Keys Ocean Explorers Expedition",
    "summary": "A one-day marine science program for 115 students, organized into four cohorts rotating through hands-on experiences led by REEF educators, from 9:00 AM to 5:00 PM.",
    "scheduleDraft": true,
    "view": "administrator",
    "purpose": "A one-day marine science program for 115 students, organized into four cohorts rotating through hands-on experiences led by REEF educators, from 9:00 AM to 5:00 PM.",
    "value": [
      {
        "title": "Real citizen science, not a demo",
        "text": "Students are trained in REEF's Volunteer Fish Survey Project methods and collect survey data using the same protocol REEF's volunteer network uses across the Caribbean and beyond."
      },
      {
        "title": "Taught by REEF educators",
        "text": "Every session and field activity is led by REEF marine science educators, with pre- and post-activity debriefs that connect what students saw to what it means."
      }
    ],
    "facts": [
      {
        "k": "Date",
        "v": "March 17, 2027"
      },
      {
        "k": "Group Size",
        "v": "115 students + 10 chaperones"
      },
      {
        "k": "Program Hours",
        "v": "9:00 AM\u20135:00 PM"
      },
      {
        "k": "Location",
        "v": "John Pennekamp Coral Reef State Park, Key Largo"
      },
      {
        "k": "Format",
        "v": "Four cohorts rotating through five hands-on experiences",
        "wide": true
      }
    ],
    "counts": {
      "students": 115,
      "chaperones": 10
    },
    "scheduleFormat": "rotation",
    "cohortSchedule": [
      {
        "cohort": "Cohort A",
        "items": [
          {
            "time": "09:00-10:00",
            "name": "Fish ID"
          },
          {
            "time": "10:00-11:00",
            "name": "Lionfish"
          },
          {
            "time": "11:00-12:00",
            "name": "Lunch"
          },
          {
            "time": "12:00-14:30",
            "name": "Boat Tour"
          },
          {
            "time": "14:30-15:30",
            "name": "Ecology"
          },
          {
            "time": "15:30-16:30",
            "name": "Species"
          }
        ]
      },
      {
        "cohort": "Cohort B",
        "items": [
          {
            "time": "09:00-10:00",
            "name": "Lionfish"
          },
          {
            "time": "10:00-11:00",
            "name": "Fish ID"
          },
          {
            "time": "11:00-12:00",
            "name": "Lunch"
          },
          {
            "time": "12:00-14:30",
            "name": "Boat Tour"
          },
          {
            "time": "14:30-15:30",
            "name": "Ecology"
          },
          {
            "time": "15:30-16:30",
            "name": "Species"
          }
        ]
      },
      {
        "cohort": "Cohort C",
        "items": [
          {
            "time": "09:00-11:30",
            "name": "Boat Tour"
          },
          {
            "time": "11:30-12:30",
            "name": "Lunch"
          },
          {
            "time": "12:30-13:30",
            "name": "Fish ID"
          },
          {
            "time": "13:30-14:30",
            "name": "Lionfish"
          },
          {
            "time": "14:30-15:30",
            "name": "Species"
          },
          {
            "time": "15:30-16:30",
            "name": "Ecology"
          }
        ]
      },
      {
        "cohort": "Cohort D",
        "items": [
          {
            "time": "09:00-11:30",
            "name": "Boat Tour"
          },
          {
            "time": "11:30-12:30",
            "name": "Lunch"
          },
          {
            "time": "12:30-13:30",
            "name": "Lionfish"
          },
          {
            "time": "13:30-14:30",
            "name": "Fish ID"
          },
          {
            "time": "14:30-15:30",
            "name": "Species"
          },
          {
            "time": "15:30-16:30",
            "name": "Ecology"
          }
        ]
      }
    ],
    "simpleSchedule": [
      {
        "time": "9:00 AM",
        "label": "Program begins. Students work in 4 small groups (cohorts) that rotate between activities."
      },
      {
        "time": "11:00 AM\u201312:30 PM",
        "label": "Picnic lunch. Each cohort has its own lunch time in this window."
      },
      {
        "time": "5:00 PM",
        "label": "Program ends."
      }
    ],
    "outcomes": [
      "Observe living coral reef habitat and marine life from the glass-bottom boat.",
      "Learn and practice the fish identification and survey methods REEF's citizen scientists use.",
      "Investigate invasive lionfish anatomy and adaptations through a guided dissection.",
      "Explore how marine ecosystems function and why some Florida Keys species are endangered.",
      "Connect what they see to REEF's ongoing reef conservation and invasive-species work."
    ],
    "responsibilities": [
      {
        "area": "Supervision",
        "text": "Teachers and adult chaperones accompanying the group are directly responsible for students at all times, including during free time and meals. An adult chaperone must accompany student groups with participants under 18."
      },
      {
        "area": "Transportation",
        "text": "Your school provides bus transportation to and from John Pennekamp Coral Reef State Park. The group arrives on three buses for a 9:00 AM drop-off, and the buses return to pick up students at 5:00 PM. Park entrance fees for all three buses are included. Transportation between the park and other locations is still being explored and is not part of this proposal."
      },
      {
        "area": "Meals",
        "text": "Lunch is not provided. Students and chaperones bring a packed lunch, and each cohort has a scheduled picnic lunch at the park. REEF staff can recommend delivery options."
      },
      {
        "area": "Activity operators",
        "text": "Boat and park activities are run by independent operators who follow their own safety protocols. The boat captain makes final decisions about schedule changes for weather or safety."
      }
    ],
    "pricing": {
      "total": "$19,920.60",
      "perStudent": "$173.22",
      "chaperones": "All 10 chaperones are complimentary.",
      "note": "Estimated total. REEF sends a revised proposal if anything that affects price changes."
    },
    "included": [
      "Glass-bottom boat tour admission for all 115 students and 10 chaperones, including the boat gratuity",
      "REEF-led programming: citizen science and fish identification training, and the lionfish lesson and dissection",
      "REEF-led afternoon programs on marine ecology and endangered species",
      "Instructional materials and REEF survey supplies for every student",
      "Lionfish specimens for the dissection",
      "John Pennekamp Coral Reef State Park entrance fees for your three buses",
      "A follow-up lesson using the survey data your students collect"
    ],
    "notIncluded": [
      "Meals \u2014 lunch time is built into the schedule, but food is not provided. Students and chaperones bring a packed lunch, and REEF staff can recommend delivery options",
      "Transportation to and from the park, which your school arranges. Transportation between the park and other locations, including REEF's campus, is still being explored and is not part of this proposal"
    ],
    "optional": [],
    "paymentTerms": [
      "A $500.00 deposit holds your group's date.",
      "Payment 2 of $9,710.30 is due Oct 1, 2026.",
      "The final payment of $9,710.30 is due Dec 17, 2026.",
      "A 10% late fee applies to payments more than 14 days past due."
    ],
    "cancellationTerms": [
      "More than 90 days before the program: full refund, minus $100 per day of scheduled programming.",
      "60\u201390 days before: 50% of the deposit held by REEF is refundable.",
      "Fewer than 60 days before: no refund.",
      "This schedule also applies if group size decreases by 50% or more. Cancellations must be made in writing."
    ],
    "termsNote": "These are REEF's standard terms. Your contract states the final terms for your group, including any vendor-specific changes.",
    "outstanding": [
      "Final student and chaperone headcount",
      "Exact cohort sizes and which students are in each cohort",
      "Teacher and chaperone assignments for each cohort",
      "Final activity order and timing (this is a planning schedule)",
      "Whether any programs can move to the REEF campus (this depends on transportation between the park and campus, which is still being explored and is not confirmed)"
    ],
    "decisionMakers": [
      {
        "name": "",
        "title": "School leadership",
        "roles": [
          "decisionMaker"
        ],
        "roleLabels": [
          "Authorized decision-maker"
        ],
        "approvalAuthority": true,
        "audiences": [
          "administrator"
        ],
        "note": "To be confirmed by the school"
      }
    ],
    "approval": {
      "enabled": true,
      "bookingId": "recqb6DGaeJRpymL2",
      "webhookUrl": null,
      "emailTo": "rose@REEF.org"
    },
    "reefContact": {
      "name": "Rose Kelly",
      "role": "Education Coordinator",
      "email": "rose@REEF.org",
      "phone": "305-852-0030"
    },
    "title": "Administrator Approval Summary",
    "audienceLabel": "Ben Gamla school leadership",
    "url": "https://reef-environmental-education-foundation.github.io/reef-program-pages/bookings/ben-gamla-charter-school/share/administrator/"
  }
};
