/* GENERATED by generate_booking_package.py -- do not hand-edit. */
window.BOOKING_DATA = {
  "docType": "proposal",
  "assetDepth": 2,
  "meta": {
    "sampleFlag": true,
    "generatedFrom": "rec4YP9ruVPOD90US",
    "generatedNote": "Generated by generate_booking_package.py from live Airtable fields on 2026-09-09."
  },
  "proposal": {
    "meta": {
      "bookingId": "rec4YP9ruVPOD90US",
      "proposalVersion": "v1",
      "proposalDate": "Aug 28, 2026",
      "programTypeLabel": "Expedition",
      "programWord": "Expedition"
    },
    "group": {
      "orgName": "ZZZ TEST ORG \u2014 Riverside Academy (Proposal QA)",
      "contactName": "Jordan Reyes",
      "gradeLevel": "7th Grade Team Lead",
      "students": 32,
      "chaperones": 5
    },
    "dates": {
      "label": "Proposed",
      "range": "Apr 13, 2027 - Apr 14, 2027"
    },
    "roadmap": {
      "steps": [
        "Inquiry",
        "Proposal Prepared",
        "Your Review",
        "Contract",
        "Confirmed"
      ],
      "currentStep": 3
    },
    "cta": {
      "primaryText": "Ready to Move Forward",
      "primaryConfirmHeadline": "Thanks \u2014 we've got your response!",
      "primaryConfirmBody": "A member of the REEF team will review your response and follow up by email with next steps to confirm your program.",
      "secondaryText": "Need to adjust something?",
      "changeFormLabel": "What would you like us to adjust?",
      "changeConfirmHeadline": "Thanks \u2014 we've got your note.",
      "changeConfirmBody": "The REEF Ocean Explorers team will follow up by email to talk through the change.",
      "contactEmail": "rose@reef.org",
      "responseWebhookUrl": "https://hooks.zapier.com/hooks/catch/28743322/4hv7eqd/"
    },
    "reefContact": {
      "name": "Rose Kelly",
      "role": "Education Coordinator",
      "photo": null,
      "welcomeLine": "Rose has been building your group's itinerary and is your direct point of contact through booking.",
      "email": "rose@reef.org",
      "phone": "305-852-0030"
    },
    "welcome": {
      "body": [
        "Rose has been building your group's itinerary and is your direct point of contact through booking."
      ],
      "signOff": "Rose Kelly"
    },
    "glance": [
      {
        "k": "Dates",
        "v": "Apr 13, 2027 - Apr 14, 2027"
      },
      {
        "k": "Group Size",
        "v": "32 students + 5 chaperones"
      },
      {
        "k": "Location",
        "v": "Key Largo (REEF)"
      },
      {
        "k": "Focus",
        "v": "Marine Ecology \u00b7 Citizen Science \u00b7 Caribbean Fish ID \u00b7 Florida Keys Ecology \u00b7 Invasive Species \u00b7 Hands-on Lab"
      }
    ],
    "pillars": [
      {
        "title": "Real citizen science, not a demo",
        "text": "Students are trained in REEF's Volunteer Fish Survey Project methods and collect survey data using the same protocol REEF's volunteer network uses across the Caribbean and beyond."
      },
      {
        "title": "Taught by REEF educators",
        "text": "Every session and field activity is led by REEF marine science educators, with pre- and post-activity debriefs that connect what students saw to what it means."
      },
      {
        "title": "The Florida Keys as the classroom",
        "text": "Programs are based at REEF's Ocean Exploration Center in Key Largo and run out into the coral reef, mangrove, and seagrass habitats that surround it."
      },
      {
        "title": "Built around your group",
        "text": "The itinerary in this proposal is shaped around your dates, group size, and what you told us your students need to get out of the trip."
      }
    ],
    "team": [
      {
        "name": "REEF Marine Science Educators",
        "role": "Program Instruction",
        "bio": "Lead every session and field activity, from fish ID training through the reef survey itself."
      },
      {
        "name": "Volunteer Fish Survey Project Staff",
        "role": "Citizen Science",
        "bio": "Run REEF's survey methodology training and help students log real observations into REEF's database."
      },
      {
        "name": "REEF Ocean Explorers Coordination",
        "role": "Trip Logistics",
        "bio": "Your planning contact for dates, headcount, vendors, and everything between booking and arrival."
      }
    ],
    "days": [
      {
        "dayNumber": 1,
        "totalDays": 2,
        "title": "From Student to Scientist",
        "theme": "Students move from REEF Campus orientation into the skills they'll apply in the field.",
        "blocks": [
          {
            "time": "Session 1",
            "tag": "Campus Activity",
            "title": "Welcome Program (arrival)",
            "description": "Students begin with a REEF Campus welcome and orientation that frames the trip as an immersive Florida Keys marine science experience."
          },
          {
            "time": "Session 2",
            "tag": "Citizen Science",
            "title": "Volunteer Fish Survey Project Training",
            "description": "Students learn how REEF volunteers identify fish and collect survey data, building the skills needed to participate in citizen science and marine biodiversity monitoring."
          },
          {
            "time": "Session 3",
            "tag": "Workshop",
            "title": "Lionfish Lesson & Dissection",
            "description": "Students investigate invasive lionfish through a hands-on lesson and guided dissection, linking anatomy and adaptation to real conservation challenges in Florida Keys ecosystems."
          }
        ],
        "studentsWill": [
          "Learn REEF's fish identification and survey methods before entering the field (Identify).",
          "Investigate invasive lionfish anatomy and adaptation through a guided dissection (Understand).",
          "Connect the lionfish investigation to REEF's ongoing invasive-species conservation work (Connect to Conservation)."
        ],
        "outcomesNote": null
      },
      {
        "dayNumber": 2,
        "totalDays": 2,
        "title": "Into the Field",
        "theme": "Students travel to real reef and coastal habitats to apply what they've learned.",
        "blocks": [
          {
            "time": "Transit",
            "tag": "Travel/Transit",
            "title": "Travel to Today's Field Site",
            "description": "Move between program locations with time built in for group transitions, preparation, and the next learning experience in the Florida Keys."
          },
          {
            "time": "Session 4",
            "tag": "Field Activity",
            "title": "Kayaking (Mangrove Tour)",
            "description": "Students explore mangroves and seagrass by kayak while investigating how coastal habitats support marine life, protect shorelines, and fit into the larger reef ecosystem (Observe)."
          },
          {
            "time": "Session 5",
            "tag": "Field Activity",
            "title": "Boat Snorkel",
            "description": "Students travel by boat to the Florida Keys coral reef to practice fish identification, observe reef ecology in the field, and connect their observations to REEF citizen science (Observe \u2192 Connect to Conservation)."
          }
        ],
        "studentsWill": [
          "Investigate mangrove and seagrass habitats and how they shelter marine life (Observe).",
          "Apply fish-ID skills on a real Florida Keys coral reef during a guided boat snorkel survey (Identify).",
          "Record field observations that feed directly into REEF's Volunteer Fish Survey Project (Connect to Conservation)."
        ],
        "outcomesNote": "Boat and kayak activities are weather- and water-condition dependent."
      }
    ],
    "included": [
      {
        "title": "Included in Your Expedition",
        "items": [
          "REEF educator-led instruction for every session and field activity",
          "Pre- and post-activity debriefs each day",
          "Citizen-science framing tied to REEF's Volunteer Fish Survey Project",
          "Offshore boat trip and guided reef snorkel survey",
          "Guided mangrove & seagrass kayak ecology tour",
          "Guided invasive lionfish lesson & dissection",
          "Fish ID and reef ecology teaching materials",
          "Lionfish dissection materials and lab setup",
          "Data sheets for the citizen-science survey activity."
        ]
      }
    ],
    "notIncluded": [
      "Transportation to and from REEF Campus, Key Largo",
      "Meals (unless a specific meal is added to your program)",
      "Personal snorkel gear, unless rental is added to your program",
      "Lodging, if your group is traveling from outside the Keys."
    ],
    "photos": {
      "overview": "photos/overview.jpeg",
      "experience": "photos/experience.png",
      "days": "photos/days.jpeg",
      "included": "photos/included.jpeg"
    },
    "photoCredits": {},
    "pricing": {
      "tileRate": {
        "label": "Per Student",
        "num": "$297.66",
        "unit": "per student for the full Expedition"
      },
      "tileChaperones": {
        "label": "Complimentary Chaperones",
        "num": "4",
        "unit": "included at no charge"
      },
      "ratioNote": "This proposal is built for 32 students and 5 chaperones, 4 of them complimentary.",
      "conditions": [
        "Every group receives 1 complimentary chaperone space for every 9 total people (students + chaperones) in the group -- REEF calculates this automatically from your group size, so it updates if your numbers change.",
        "Chaperones beyond the complimentary count shown above are billed at the same per-student rate."
      ],
      "estimatedTotal": "$9,822.75",
      "estimatedTotalNote": "<strong>$9,822.75</strong> estimated total for the group and dates above, including REEF program fees and any applicable discount or sales tax. This estimate is valid for the group size and dates shown here -- REEF will re-quote automatically if activities, headcount, or dates change.",
      "assumptions": [
        "Based on a group of 32 students and 5 chaperones across both proposed program days.",
        "Rate assumes both days run as outlined",
        "Pricing will be revisited if activities, headcount, or dates change.",
        "Boat and kayak activities are weather- and water-condition dependent."
      ],
      "whatCouldChange": []
    }
  }
};
