/* GENERATED by generate_booking_package.py -- do not hand-edit. */
window.BOOKING_DATA = {
  "docType": "pretrip",
  "assetDepth": 2,
  "meta": {
    "sampleFlag": false,
    "generatedFrom": "rec4YP9ruVPOD90US",
    "generatedNote": "Generated by generate_booking_package.py from live Airtable fields on 2026-09-03."
  },
  "program": {
    "name": "Florida Keys Marine Science Expedition",
    "track": "Expedition",
    "groupName": "ZZZ TEST ORG \u2014 Riverside Academy (Proposal QA)",
    "schoolOrg": "ZZZ TEST ORG \u2014 Riverside Academy (Proposal QA)",
    "gradeLevel": "7th Grade Team Lead",
    "groupSize": "32 Students / 5 Chaperones",
    "location": "REEF Campus, Key Largo",
    "dates": {
      "label": "Proposed",
      "range": "Apr 13, 2027 - Apr 14, 2027"
    }
  },
  "contacts": {
    "educatorName": "Jordan Reyes",
    "reefEducatorName": "Rose Kelly",
    "reefEducatorTitle": "Education Coordinator",
    "reefEducatorWelcomeLine": "Rose has been building your group's itinerary and is your direct point of contact through booking.",
    "reefPhone": "305-852-0030",
    "reefEmail": "rose@reef.org"
  },
  "hero": {
    "kicker": "OCEAN EXPLORERS\nEXPEDITION PACKET",
    "eyebrowTag": "Florida Keys Marine Science Expedition",
    "headline": "From Student to Scientist in Key Largo",
    "promise": "Turn the ocean into your classroom. Your students won't just study marine science -- they become part of it.",
    "imageUrl": "../../assets/photos/hero-reef-shark.jpg",
    "imageCredit": "Photo: Jeffrey Haines / REEF"
  },
  "actionNeeded": {
    "show": true,
    "headline": "Your contract is being prepared",
    "detail": "REEF is finalizing your agreement based on the proposal you approved. You'll receive it here once it's ready to sign.",
    "ctaText": null,
    "ctaUrl": null
  },
  "agreement": {
    "status": "Not Sent",
    "zohoSignUrl": null,
    "lastUpdated": null
  },
  "paymentSchedule": {
    "tier": "Standard (>180 days out): $1,000 deposit + 2 payments",
    "items": [
      {
        "label": "Deposit (due now)",
        "amount": "$1,000.00",
        "dueDate": null
      },
      {
        "label": "Payment 2",
        "amount": "$4,411.38",
        "dueDate": "Oct 15, 2026"
      },
      {
        "label": "Final Payment",
        "amount": "$4,411.38",
        "dueDate": "Jan 13, 2027"
      }
    ],
    "total": "$9,822.75",
    "note": "Generated from REEF Bookings' payment-schedule fields (added 2026-09-03); confirm the 50/50 Payment 2 / Final split assumption before treating as final."
  },
  "nextSteps": {
    "items": [
      "Review and sign your agreement once it's sent (see above).",
      "Return your group's signed waivers and health/medical forms.",
      "Confirm final headcount with your REEF educator at least 2 weeks before arrival.",
      "Reach out any time with questions before your expedition."
    ]
  },
  "welcome": {
    "body": [
      "We're glad your group is joining us. This packet lays out what to expect from your Florida Keys Marine Science Expedition -- where your students will identify reef fish, explore real coral reef, mangrove, and seagrass habitats, and practice the same citizen-science methods REEF's volunteer network uses across the Caribbean and beyond.",
      "This is not a sightseeing trip. It's a working expedition: your students will observe, identify, survey, investigate, and contribute -- and leave with a real sense of what it means to practice marine science, not just read about it."
    ],
    "signOff": "The REEF Ocean Explorers Team"
  },
  "glanceNote": "A quick-scan summary for planning. Full detail -- including \u201cstudents will\u201d outcomes and gear notes -- follows on the day-by-day pages.",
  "days": [
    {
      "dayNumber": 1,
      "totalDays": 2,
      "title": "From Student to Scientist",
      "theme": "Students move from REEF Campus orientation into the skills they'll apply in the field.",
      "morningLabel": "Welcome Program (arrival)",
      "afternoonLabel": "Lionfish Lesson & Dissection",
      "learningOutcome": "Learn REEF's fish identification and survey methods before entering the field; Investigate invasive lionfish anatomy and adaptation through a guided dissection",
      "blocks": [
        {
          "time": "Session 1",
          "tag": "Campus Activity",
          "title": "Welcome Program (arrival)",
          "description": "Students begin with a REEF Campus welcome and orientation that frames the trip as an immersive Florida Keys marine science experience."
        },
        {
          "time": "Session 2",
          "tag": "Citizen Science",
          "title": "Volunteer Fish Survey Project Training",
          "description": "Students learn how REEF volunteers identify fish and collect survey data, building the skills needed to participate in citizen science and marine biodiversity monitoring."
        },
        {
          "time": "Session 2",
          "tag": "Workshop",
          "title": "Lionfish Lesson & Dissection",
          "description": "Students investigate invasive lionfish through a hands-on lesson and guided dissection, linking anatomy and adaptation to real conservation challenges in Florida Keys ecosystems."
        }
      ],
      "studentsWill": [
        "Learn REEF's fish identification and survey methods before entering the field (Identify).",
        "Investigate invasive lionfish anatomy and adaptation through a guided dissection (Understand).",
        "Connect the lionfish investigation to REEF's ongoing invasive-species conservation work (Connect to Conservation)."
      ],
      "outcomesNote": null
    },
    {
      "dayNumber": 2,
      "totalDays": 2,
      "title": "Into the Field",
      "theme": "Students travel to real reef and coastal habitats to apply what they've learned.",
      "morningLabel": "Travel / Transit",
      "afternoonLabel": "Boat Snorkel",
      "learningOutcome": "Investigate mangrove and seagrass habitats and how they shelter marine life; Apply fish-ID skills on a real Florida Keys coral reef during a guided boat snorkel survey",
      "blocks": [
        {
          "time": "Transit",
          "tag": "Travel/Transit",
          "title": "Travel / Transit",
          "description": "Move between program locations with time built in for group transitions, preparation, and the next learning experience in the Florida Keys."
        },
        {
          "time": "Session 3",
          "tag": "Field Activity",
          "title": "Kayaking (Mangrove Tour)",
          "description": "Students explore mangroves and seagrass by kayak while investigating how coastal habitats support marine life, protect shorelines, and fit into the larger reef ecosystem (Observe)."
        },
        {
          "time": "Session 4",
          "tag": "Field Activity",
          "title": "Boat Snorkel",
          "description": "Students travel by boat to the Florida Keys coral reef to practice fish identification, observe reef ecology in the field, and connect their observations to REEF citizen science (Observe \u2192 Connect to Conservation)."
        }
      ],
      "studentsWill": [
        "Investigate mangrove and seagrass habitats and how they shelter marine life (Observe).",
        "Apply fish-ID skills on a real Florida Keys coral reef during a guided boat snorkel survey (Identify).",
        "Record field observations that feed directly into REEF's Volunteer Fish Survey Project (Connect to Conservation)."
      ],
      "outcomesNote": "Boat and kayak activities are weather- and water-condition dependent."
    }
  ]
};
