/* GENERATED by generate_booking_package.py -- do not hand-edit. Contains ONLY the fields this audience view shows. */
window.BOOKING_DATA = {
  "docType": "audience",
  "assetDepth": 4,
  "meta": {
    "sampleFlag": false
  },
  "view": {
    "status": "draft",
    "statusLabel": "Draft",
    "version": "v1",
    "lastUpdated": "Oct 1, 2026",
    "orgName": "Ben Gamla Charter School",
    "dateLine": "March 17, 2027",
    "hours": "9:00 AM\u20135:00 PM",
    "programName": "Florida Keys Ocean Explorers Expedition",
    "summary": "A one-day marine science program for 115 students, organized into four cohorts rotating through hands-on experiences led by REEF educators, from 9:00 AM to 5:00 PM.",
    "scheduleDraft": true,
    "view": "student",
    "headline": "A day on the reef at John Pennekamp",
    "intro": "You'll spend the day with REEF educators, rotating with your cohort through hands-on marine science experiences at John Pennekamp Coral Reef State Park.",
    "experiences": [
      {
        "title": "Glass-Bottom Boat Tour",
        "text": "Students view living coral reef habitat and the fish that depend on it from a glass-bottom boat, with a REEF educator helping them connect what they see to how healthy reefs work.",
        "color": 0
      },
      {
        "title": "Citizen Science & Fish Identification",
        "text": "Students learn how REEF's volunteer divers and snorkelers identify fish and record what they see, then practice the same identification and survey skills used in REEF's Volunteer Fish Survey Project.",
        "color": 1
      },
      {
        "title": "Lionfish Lesson & Dissection",
        "text": "Students investigate invasive lionfish through a guided dissection, looking at anatomy and adaptations and learning why lionfish are a conservation challenge for Florida Keys reefs.",
        "color": 2
      },
      {
        "title": "Marine Ecology",
        "text": "A REEF educator-led program on how reef, seagrass, and mangrove communities work and how the species within them depend on one another. Two cohorts join each one-hour session.",
        "color": 4
      },
      {
        "title": "Endangered Species",
        "text": "A REEF educator-led program on threatened and endangered species of the Florida Keys, why they are at risk, and what people can do to help protect them. Two cohorts join each one-hour session.",
        "color": 5
      }
    ],
    "topics": [
      "Florida Keys Ecology",
      "Marine Ecology",
      "Invasive Species",
      "Hands-on Lab",
      "Citizen Science",
      "Caribbean Fish ID"
    ],
    "feel": [
      "You'll move through the day with your cohort, a small group of classmates.",
      "You'll spend time on the water, at a hands-on lab, and outdoors at the park."
    ],
    "bring": [
      "A packed lunch"
    ],
    "classroomPrep": [
      "Look at pictures of reef fish and practice naming a few before the trip."
    ],
    "title": "Student Preview",
    "audienceLabel": "Ben Gamla students",
    "url": "https://reef-environmental-education-foundation.github.io/reef-program-pages/bookings/ben-gamla-charter-school/share/student/"
  }
};
